!	TOPS-20 SYSTEM PROGRAM VERIFICATION PROCEDURE
!
!VERBAS.BAT	VERSION 1	4/15/76
!
!CONTROL FILE TO VERIFY EXISTENCE AND MINIMUM FUNCTIONING
! OF BASIC SYSTEM
!
!*****NOTE*****	THIS CONTROL FILE REQUIRES THAT THE FILE
!		ERRORS.LOG ALREADY BE CREATED
!
!************************************************************
!
!
!
!SYS:BASIC.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@COPY SYS:BASIC.EXE (TO) NUL:
@IF (NOERROR) @GOTO BASIC1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERBAS.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:BASIC.EXE	++++
@++++	END OF ERROR MESSAGE VERBAS.BAT		++++
@
@
!
BASIC1::
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
@BASIC
*OLD VERBAS.BAS
*RUN
*MONITOR
@IF (NOERROR) @GOTO BAS2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERBAS.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:BASIC.EXE++
@++++	END OF ERROR MESSAGE VERBAS.BAT		++++
@
@
!
BAS2::
!
!
!
!CHECK FOR EXISTENCE OF A HELP FILE
@COPY SYS:BASIC.HLP (TO) NUL:
@IF (NOERROR) @GOTO BAS4::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERBAS.BAT ERROR		++++
@++++	HELP FILE MISSING FOR SYS:BASIC.EXE	++++
@++++	END OF ERROR MESSAGE VERBAS.BAT		++++
@
@
!
BAS4::
!
@QUEUE INP:VERIF1=/MODIFY/DEPENDENCY:-1
