!VERIFY.BAT	VERSION 1	6/1/76
!
!BATCH CONTROL FILE TO PERFORM CURSORY VERIFICATION OF THE EXISTENCE
! AND FUNCTIONING OF ALL DELIVERABLE TOPS-20 SOFTWARE
!
!TABLE OF CONTENTS (SEQUENCE OF TESTS):
!
!	<SYSTEM>MONITR.EXE
!	<SYSTEM>MONBCH.EXE
!	<SYSTEM>MONMED.EXE
!	<SYSTEM>MONMIN.EXE
!	<SYSTEM>MONSML.EXE
!	<SYSTEM>EXEC.EXE
!	<SYSTEM>DUMP.EXE
!	<SYSTEM>CHECKPOINT.BIN
!	<SYSTEM>ERRMES.BIN
!	<SYSTEM>SETSPD.EXE
!	<SYSTEM>PTYCON.ATO
!	<SYSTEM>SYSJOB.RUN
!	<SYSTEM>CHECKD.EXE
!	MACRO
!	LINK
!	DDT
!	EXECUTION OF SIMPLE MACRO PROGRAM VERIFY.MAC
!	MACSYM.UNV
!	MONSYM.UNV
!	EDIT
!	CREF
!	HELP
!	PLEASE
!	MAIL
!	RDMAIL
!	FILCOM
!	CHECKD
!	CHKPNT
!	DLUSER
!	OPLEAS
!	MAILER
!	OVRLAY
!	DUMPER
!	PTYCON
!	<SYSTEM>SYSJOB
!	INFO
!	WATCH
!	SYSERR
!	ULIST
!	TRANSL
!	ACCT20
!	ACCTPR
!	PA1050
!	RUNOFF
!	MAKLIB
!	MAKVFU
!	MAKRAM
!	QUASAR
!	LPTSPL
!	BATCON
!	QUENCH
!	QMANGR
!
!
!
!WRITE A HEADER INTO ERRORS.LOG
@RUN WRTERR
@
@
!************************************************************
!
!WHEEL CAPABILITY REQUIRED TO ACCESS <SYSTEM> FILES.
!
@ENABLE
!
!************************************************************
!
!<SYSTEM>MONITR.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:<SYSTEM>MONITR.EXE
@IF (NOERROR) @GOTO MONIT1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR	++++
@++++	COULD NOT GET FILE MONITR.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT	++++
@
@
!
MONIT1::
@INFORMATION (ABOUT) VERSION
!
!************************************************************
!
!<SYSTEM>MONBCH.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:<SYSTEM>MONBCH.EXE
@IF (NOERROR) @GOTO MONBC1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR	++++
@++++	COULD NOT GET FILE MONBCH.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT	++++
@
@
!
MONBC1::
@INFORMATION (ABOUT) VERSION
!
!************************************************************
!
!<SYSTEM>MONMED.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:<SYSTEM>MONMED.EXE
@IF (NOERROR) @GOTO MONME1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR	++++
@++++	COULD NOT GET FILE MONMED.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT	++++
@
@
!
MONME1::
@INFORMATION (ABOUT) VERSION
!
!************************************************************
!
!<SYSTEM>MONMIN.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:<SYSTEM>MONMIN.EXE
@IF (NOERROR) @GOTO MONMI1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR	++++
@++++	COULD NOT GET FILE MONMIN.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT	++++
@
@
!
MONMI1::
@INFORMATION (ABOUT) VERSION
!
!************************************************************
!
!<SYSTEM>MONSML.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:<SYSTEM>MONSML.EXE
@IF (NOERROR) @GOTO MONSM1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR	++++
@++++	COULD NOT GET FILE MONSML.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT	++++
@
@
!
MONSM1::
@INFORMATION (ABOUT) VERSION
!
!************************************************************
!
!<SYSTEM>EXEC.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:<SYSTEM>EXEC.EXE
@IF (NOERROR) @GOTO EXEC1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR	++++
@++++	COULD NOT GET FILE EXEC.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT	++++
@
@
!
EXEC1::
@INFORMATION (ABOUT) VERSION
!
!TEST RUDIMENTARY FUNCTIONING OF EXEC
!
@START
@POP
@IF (NOERROR) @GOTO EXEC2::
@APPEND TTY:: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMANDS TO 		++++
@++++	A PUSHED COPY OF THE EXEC		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
EXEC2::
!
!************************************************************
!
!<SYSTEM>DUMP.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@ENABLE
!
@COPY SYS:<SYSTEM>DUMP.EXE (TO) NUL:
@IF (NOERROR) @GOTO DUMP1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE <SYSTEM>DUMP.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
DUMP1::
!
!
!
!************************************************************
!
!<SYSTEM>CHECKPOINT.BIN TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@ENABLE
@COPY SYS:<SYSTEM>CHECKPOINT.BIN (TO) NUL:
@IF (NOERROR) @GOTO CHKPN1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE <SYSTEM>CHECKPOINT.BIN+++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
CHKPN1::
!
!
!************************************************************
!
!<SYSTEM>ERRMES.BIN TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@COPY SYS:<SYSTEM>ERRMES.BIN (TO) NUL:
@IF (NOERROR) @GOTO ERRME1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT FIND FILE <SYSTEM>ERRMES.BIN	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
ERRME1::
!
!
!
!************************************************************
!
!<SYSTEM>SETSPD.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:<SYSTEM>SETSPD.EXE
@IF (NOERROR) @GOTO SETSP1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE <SYSTEM>SETSPD.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
SETSP1::
@INFORMATION (ABOUT) VERSION
!
!
!
!************************************************************
!
!<SYSTEM>PTYCON.ATO TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@COPY SYS:<SYSTEM>PTYCON.ATO (TO) NUL:
@IF (NOERROR) @GOTO PTYC1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT FIND FILE <SYSTEM>PTYCON.ATO	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
PTYC1::
!
!
!************************************************************
!
!<SYSTEM>SYSJOB.RUN TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@COPY SYS:<SYSTEM>SYSJOB.RUN (TO) NUL:
@IF (NOERROR) @GOTO SYSJ1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT FIND FILE <SYSTEM>SYSJOB.RUN	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
SYSJ1::
!
!************************************************************
!
!<SYSTEM>CHECKD.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@COPY SYS:<SYSTEM>CHECKD.EXE (TO) NUL:
@IF (NOERROR) @GOTO CHEC1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT FIND FILE <SYSTEM>CHECKD.EXE++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
CHEC1::
!
!
!
!
!************************************************************
!
!SYS:MACRO TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:MACRO
@IF (NOERROR) @GOTO MACRO1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE MACRO		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MACRO1::
@INFORMATION (ABOUT) VERSION
!
!
!TEST RUDIMENTARY FUNCTIONING OF MACRO
!
@DELETE VERIFY.REL,VERIFY.CRF,VERIFY.LST
!
@RESET
@SYS:MACRO
*VERIFY,VERIFY/C=VERIFY
@IF (NOERROR) @GOTO MACRO2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO MACRO	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MACRO2::
!
@
!TEST TO SEE IF VERIFY.REL HAS BEEN CREATED
@COPY VERIFY.REL (TO) NUL:
@IF (NOERROR) @GOTO MACRO3::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	FILE VERIFY.REL APPARENTLY NOT CREATED	++++
@++++	BY MACRO 				++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MACRO3::
!
!TEST TO SEE IF VERIFY.CRF WAS CREATED 
@COPY VERIFY.CRF (TO) NUL:
@IF (NOERROR) @GOTO MACRO4::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	FILE VERIFY.CRF APPARENTLY NOT CREATED	++++
@++++	BY MACRO 				++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MACRO4::
!
!
!************************************************************
!
!SYS:LINK TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:LINK
@IF (NOERROR) @GOTO LINK1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE LINK			++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
LINK1::
@INFORMATION (ABOUT) VERSION
!
!TEST RUDIMENTARY FUNCTIONING OF LINK
!
@RESET
@SYS:LINK
*VERIFY/GO
@IF (NOERROR) @GOTO LINK2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND  TO LINK		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
LINK2::
!
!************************************************************
!
!DDT TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@DDT
@IF (NOERROR) @GOTO DDT1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT EXECUTE A DDT COMMAND		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
!TEST FOR RUDIMENTARY FUNCTIONING OF DDT
!
DDT1::
!
=VERIFY:
=STKSIZ=
@
!
!STKSIZ ABOVE SHOULD BE EQUAL TO 10
!
@
@IF (NOERROR) @GOTO DDT2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO DDT	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
DDT2::
!***********************************************************
!
!TO WRAP UP THE LAST FEW TESTS, EXECUTE THE BRIEF PROGRAM
! JUST ASSEMBLED AND LOADED
!
@EXECUTE VERIFY
@IF (NOERROR) @GOTO VERIF1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT EXECUTE VERIFY.REL CORRECTLY	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
@
!
VERIF1::
! 
!************************************************************
!
!SYS:MACSYM.UNV TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@COPY SYS:MACSYM.UNV (TO) NUL:
@IF (NOERROR) @GOTO MACSY1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE MACSYM.UNV		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MACSY1::
!
!************************************************************
!
!SYS:MONSYM.UNV TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@COPY SYS:MONSYM.UNV (TO) NUL:
@IF (NOERROR) @GOTO MONSY1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT FIND FILE SYS:MONSYM.UNV	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MONSY1::
!
!************************************************************
!
!SYS:EDIT TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:EDIT
@IF (NOERROR) @GOTO EDIT1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE EDIT			++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
EDIT1::
@INFORMATION (ABOUT) VERSION
!
!TEST RUDIMENTARY FUNCTIONING OF EDIT
!
@RESET
@DELETE EDIT.EDI
@EDIT EDIT.EDI
*TEST LINE
*
*E
@IF (NOERROR) @GOTO EDIT2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO EDIT	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
EDIT2::
!
!TEST TO SEE IF FILE EDIT.EDI WAS CREATED PROPERLY
@TYPE EDIT.EDI
@IF (NOERROR) @GOTO EDIT3::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	FILE EDIT.EDI APPARENTLY NOT CREATED	++++
@++++	BY EDIT					++++
@
@
!
EDIT3::
!
!************************************************************
!
!SYS:CREF TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:CREF
@IF (NOERROR) @GOTO CREF1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE CREF			++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
CREF1::
@INFORMATION (ABOUT) VERSION
!
!TEST RUDIMETARY FUNCTIONING OF CREF.
! THIS WILL CAUSE A CREF LISTING OF THE PROGRAM VERIFY.MAC,
! ASSEMBLED PREVIOUSLY, TO BE QUEUED TO THE PRINTER.
!
@RESET
@CREF
*VERIFY.LST=VERIFY.CRF
@IF (NOERROR) @GOTO CREF2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO CREF	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
CREF2::
!
!************************************************************
!
!SYS:HELP TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:HELP.EXE
@IF (NOERROR) @GOTO HELP1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:HELP.EXE		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
HELP1::
@INFORMATION (ABOUT) VERSION
!
!TEST RUDIMENTARY FUNCTIONING OF HELP
!
@RESET
@HELP PLEASE
@IF (NOERROR) @GOTO HELP2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT USE HELP			++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
HELP2::
!
!
!************************************************************
!
!SYS:PLEASE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:PLEASE
@IF (NOERROR) @GOTO PLEAS1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:PLEASE		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
PLEAS1::
@INFORMATION (ABOUT) VERSION
!
!IT IS NOT POSSIBLE TO TEST PLEASE UNDER BATCH.
!
!************************************************************
!
!SYS:MAIL TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:MAIL
@IF (NOERROR) @GOTO MAIL1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:MAIL		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MAIL1::
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
!
!THIS TEST OF MAIL SENDS A MESSAGE TO THIS JOB (.)
@SYS:MAIL
*.
*
*SUBJECT - TEST
*MESSAGE - TEST
*
@IF (NOERROR) @GOTO MAIL2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:MAIL	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MAIL2::
!
!************************************************************
!
!RDMAIL TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:RDMAIL
@IF (NOERROR) @GOTO RDMAI1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE RDMAIL		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
RDMAI1::
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
!ATTEMPT TO READ THE MESSAGE JUST SENT.
@RDMAIL
*
@IF (NOERROR) @GOTO RDMAI2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO RDMAIL	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
RDMAI2::
!
!************************************************************
!
!SYS:FILCOM TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:FILCOM
@IF (NOERROR) @GOTO FILCO1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:FILCOM		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
FILCO1::
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
@COPY TTY: (TO) FILCOM.TST
@TEST OF FILCOM
@
@COPY FILCOM.TST (TO) FILC01.TST
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT			++++
@++++	(THIS MESSAGE WILL ALWAYS		++++
@++++	APPEAR IN ERRORS.LOG)			++++
@++++	TEST OF FILCOM.  ANY DISCREPANCIES	++++
@++++	BETWEEN TWO SUPPOSEDLY EQUAL FILES	++++
@++++	WILL BE SANDWICHED BETWEEN TWO LINES	++++
@++++	BELOW:					++++
@++++	THIS LINE PRECEEDS ANY DISCREPANCIES	++++
@
@SYS:FILCOM
*ERRORS.TMP=FILCOM.TST,FILC01.TST
@IF (NOERROR) @GOTO FILCO2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:FILCOM	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
FILCO2::
@APPEND ERRORS.TMP (TO) ERRORS.LOG
@DELETE ERRORS.TMP
@APPEND TTY: (TO) ERRORS.LOG
@++++	THIS LINE FOLLOWS ANY DISCREPANCIES	++++
@++++	END OF FILCOM TEST IN VERIFY.BAT	++++
@
@
!
!************************************************************
!
!SYS:CHECKD TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:CHECKD
@IF (NOERROR) @GOTO CHECK1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:CHECKD		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
CHECK1::
@INFORMATION (ABOUT) VERSION
!IT IS NOT POSSIBLE TO TEST CHECKD UNDER BATCH
!
!CHECK FOR EXISTENCE OF A HELP FILE
@COPY SYS:CHECKD.HLP (TO) NUL:
@IF (NOERROR) @GOTO CHECK4::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	HELP FILE MISSING FOR SYS:CHECKD	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
CHECK4::
@EXPUNGE
!
!
!************************************************************
!
!SYS:CHKPNT.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:CHKPNT.EXE
@IF (NOERROR) @GOTO CHK1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:CHKPNT.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
CHK1::
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
@SYS:CHKPNT.EXE
*HELP
@IF (NOERROR) @GOTO CHK2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:CHKPNT.EXE+
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
CHK2::
!
!
!CHECK FOR EXISTENCE OF A HELP FILE
@COPY SYS:CHKPNT.HLP (TO) NUL:
@IF (NOERROR) @GOTO CHK4::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	HELP FILE MISSING FOR SYS:CHKPNT.EXE		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
CHK4::
!
!
!************************************************************
!
!SYS:DLUSER TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:DLUSER
@IF (NOERROR) @GOTO DLUSE1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:DLUSER		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
DLUSE1::
@INFORMATION (ABOUT) VERSION
!
!
!CHECK FOR EXISTENCE OF A HELP FILE
@COPY SYS:DLUSER.HLP (TO) NUL:
@IF (NOERROR) @GOTO DLUSE4::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	HELP FILE MISSING FOR SYS:DLUSER	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
DLUSE4::
@EXPUNGE
!
!
!************************************************************
!
!SYS:OPLEAS.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:OPLEAS.EXE
@IF (NOERROR) @GOTO OPLEA1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:OPLEAS.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
OPLEA1::
@INFORMATION (ABOUT) VERSION
!
!
@EXPUNGE
!
!
!************************************************************
!
!SYS:MAILER TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:MAILER
@IF (NOERROR) @GOTO MAILE1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:MAILER		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MAILE1::
@INFORMATION (ABOUT) VERSION
!
!
!
!************************************************************
!
!SYS:OVRLAY.REL TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@COPY SYS:OVRLAY.REL (TO) NUL:
@IF (NOERROR) @GOTO OVRLA1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:OVRLAY.REL	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
OVRLA1::
!
!
!
!************************************************************
!
!SYS:DUMPER TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:DUMPER
@IF (NOERROR) @GOTO DUMPE1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:DUMPER		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
DUMPE1::
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
@SYS:DUMPER
*?
@IF (NOERROR) @GOTO DUMPE2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:DUMPER	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
DUMPE2::
!
!
!************************************************************
!
!SYS:PTYCON TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:PTYCON
@IF (NOERROR) @GOTO PTYCO1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:PTYCON		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
PTYCO1::
@INFORMATION (ABOUT) VERSION
!
!IT IS NOT POSSIBLE TO TEST PTYCON UNDER BATCH
!
!
!************************************************************
!
!<SYSTEM>SYSJOB TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:<SYSTEM>SYSJOB
@IF (NOERROR) @GOTO SYSJO1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE <SYSTEM>SYSJOB	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
SYSJO1::
@INFORMATION (ABOUT) VERSION
!
!IT IS NOT POSSIBLE TO TEST SYSJOB UNDER BATCH
!
!
!
!************************************************************
!
!END OF REQUIREMENT FOR WHEEL CAPABILITY.
!
@DISABLE
!
!************************************************************
!
!SYS:INFO TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:INFO
@IF (NOERROR) @GOTO INFO1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:INFO		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
INFO1::
@INFORMATION (ABOUT) VERSION
!
!IT IS NOT POSSIBLE TO TEST INFO UNDER BATCH
!
!
!************************************************************
!
!SYS:WATCH TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:WATCH
@IF (NOERROR) @GOTO WATCH1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:WATCH		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
WATCH1::
@INFORMATION (ABOUT) VERSION
!
!NO TEST OF WATCH IS PROVIDED BECAUSE IT IS NOT POSSIBLE TO
! EXIT UNDER BATCH
!
!************************************************************
!
!SYS:SYSERR TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:SYSERR
@IF (NOERROR) @GOTO SYSER1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:SYSERR		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
SYSER1::
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
@SYS:SYSERR
*TTY:=/HELP
!
!
!************************************************************
!
!SYS:ULIST TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:ULIST
@IF (NOERROR) @GOTO ULIST1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:ULIST		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
ULIST1::
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
@SYS:ULIST
*MINI
*OUTPUT (TO FILE) TTY:
*BEGIN
@IF (NOERROR) @GOTO ULIST2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:ULIST	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
ULIST2::
!
!
!
!************************************************************
!
!
!SYS:TRANSL TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:TRANSL
@IF (NOERROR) @GOTO TRANS1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:TRANSL		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
TRANS1::
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
@SYS:TRANSL
*<SYSTEM>
@IF (NOERROR) @GOTO TRANS2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:TRANSL	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
TRANS2::
!
!
!
!
!************************************************************
!
!SYS:ACCT20 TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:ACCT20
@IF (NOERROR) @GOTO ACCT21::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:ACCT20		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
ACCT21::
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
@SYS:ACCT20
*?
@IF (NOERROR) @GOTO ACCT22::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:ACCT20	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
ACCT22::
!
!
!CHECK FOR EXISTENCE OF A HELP FILE
@COPY SYS:ACCT20.HLP (TO) NUL:
@IF (NOERROR) @GOTO ACCT24::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	HELP FILE MISSING FOR ACCT20		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
ACCT24::
@EXPUNGE
!
!THE FOLLOWING LINE SETS UP A DUMMY VERSION NUMBER OF BLANKS
! FOR THE VERIFY PACKAGE.
!PROGRAM IS ACCT20
!
!
!************************************************************
!
!SYS:ACCTPR TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:ACCTPR
@IF (NOERROR) @GOTO ACCTP1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:ACCTPR		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
ACCTP1::
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
@SYS:ACCTPR
*HELP
@IF (NOERROR) @GOTO ACCTP2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR			++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:ACCTPR		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT			++++
@
@
!
ACCTP2::
!
!
!CHECK FOR EXISTENCE OF A HELP FILE
@COPY SYS:ACCTPR.HLP (TO) NUL:
@IF (NOERROR) @GOTO ACCTP4::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	HELP FILE MISSING FOR SYS:ACCTPR	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
ACCTP4::
@EXPUNGE
!
!
!
!************************************************************
!
!SYS:PA1050 TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:PA1050
@IF (NOERROR) @GOTO PA1051::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:PA1050		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
PA1051::
@INFORMATION (ABOUT) VERSION
!
!NO DIRECT TEST OF PA1050 IS POSSIBLE WITHIN THIS BATCH 
! CONTROL FILE.  HOWEVER, THE MODULE HAS ALREADY BEEN
! USED BY MANY OTHER SYSTEM PROGRAMS WITHIN THIS BATCH RUN.
!
!
!
!
!
!************************************************************
!
!SYS:RUNOFF TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:RUNOFF
@IF (NOERROR) @GOTO RUNOF1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:RUNOFF		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
RUNOF1::
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
@COPY TTY: (TO) RUNOFF.TST
@THIS
@IS
@A
@TEST
@
!
@RESET
@SYS:RUNOFF
*RUNOFF.MEM=RUNOFF.TST
@IF (NOERROR) @GOTO RUNOF2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:RUNOFF	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
RUNOF2::
!
@TYPE RUNOFF.MEM
@IF (NOERROR) @GOTO RUNOF3::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT TYPE FILE RUNOFF.MEM		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
RUNOF3::
!
!************************************************************
!
!SYS:MAKLIB TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:MAKLIB
@IF (NOERROR) @GOTO MAKLI1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:MAKLIB		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MAKLI1::
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
@SYS:MAKLIB
*VERIFY.LIB=VERIFY.REL/APPEND
@IF (NOERROR) @GOTO MAKLI2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:MAKLIB	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MAKLI2::
@COPY VERIFY.LIB (TO) NUL:
@IF (NOERROR) @GOTO MAKLI3::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	PROBLEM IN TESTING OF SYS:MAKLIB	++++
@++++	COULD NOT FIND FILE VERIFY.LIB		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MAKLI3::
!
!
!************************************************************
!
!SYS:MAKVFU.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:MAKVFU.EXE
@IF (NOERROR) @GOTO MAKVF1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:MAKVFU.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MAKVF1::
!
!
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
@SYS:MAKVFU.EXE
*INFORMATION
@IF (NOERROR) @GOTO MAKVF2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:MAKVFU.EXE+
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MAKVF2::
!
!
!CHECK FOR EXISTENCE OF A HELP FILE
@COPY SYS:MAKVFU.HLP (TO) NUL:
@IF (NOERROR) @GOTO MAKVF4::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	HELP FILE MISSING FOR SYS:MAKVFU.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MAKVF4::
!
!
!
!************************************************************
!
!SYS:MAKRAM.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:MAKRAM.EXE
@IF (NOERROR) @GOTO MAKRA1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:MAKRAM.EXE			++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MAKRA1::
!
@INFORMATION (ABOUT) VERSION
!
!NEXT, DO A RUDIMENTARY TEST OF FUNCTIONING OF SOFTWARE PRODUCT
!
!
@RESET
@SYS:MAKRAM.EXE
*HELP
@IF (NOERROR) @GOTO MAKRA2::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GIVE COMMAND(S) TO SYS:MAKRAM.EXE+
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MAKRA2::
!
!
!CHECK FOR EXISTENCE OF A HELP FILE
@COPY SYS:MAKRAM.HLP (TO) NUL:
@IF (NOERROR) @GOTO MAKRA4::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	HELP FILE MISSING FOR SYS:MAKRAM.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
MAKRA4::
!
!
!************************************************************
!
!SYS:QUASAR.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:QUASAR.EXE
@IF (NOERROR) @GOTO QUAS1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:QUASAR.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
QUAS1::
!
@INFORMATION (ABOUT) VERSION
!
!
!************************************************************
!
!SYS:LPTSPL.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:LPTSPL.EXE
@IF (NOERROR) @GOTO LPTSP1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:LPTSPL.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
LPTSP1::
!
@INFORMATION (ABOUT) VERSION
!
LPTSP2::
!
!
!CHECK FOR EXISTENCE OF A HELP FILE
@COPY SYS:LPTSPL.HLP (TO) NUL:
@IF (NOERROR) @GOTO LPTSP4::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	HELP FILE MISSING FOR SYS:LPTSPL.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
LPTSP4::
!
!
!************************************************************
!
!SYS:BATCON.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:BATCON.EXE
@IF (NOERROR) @GOTO BATC1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:BATCON.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
BATC1::
!
@INFORMATION (ABOUT) VERSION
!
!************************************************************
!
!SYS:QUENCH.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:QUENCH.EXE
@IF (NOERROR) @GOTO QUEN1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:QUENCH.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
QUEN1::
!
@INFORMATION (ABOUT) VERSION
!
QUEN2::
!
!
!CHECK FOR EXISTENCE OF A HELP FILE
@COPY SYS:QUEUE.HLP (TO) NUL:
@IF (NOERROR) @GOTO QUEN4::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	HELP FILE MISSING FOR SYS:QUENCH.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
QUEN4::
!
!
!************************************************************
!
!SYS:QMANGR.EXE TEST
!
!FIRST TEST FOR EXISTENCE OF FILE.
!
@GET SYS:QMANGR.EXE
@IF (NOERROR) @GOTO QMAN1::
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	COULD NOT GET FILE SYS:QMANGR.EXE	++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!
QMAN1::
!
@INFORMATION (ABOUT) VERSION
!
!
!***********************************************************
!NOTE -- VERIF1.BAT MUST BE RUN AFTER ALL THE BATCH STREAMS FOR
! UNBUNDLED PRODUCTS, AND AFTER THE CURRENT BATCH FILE (VERIFY.BAT)
! HAS COMPLETED.  THEREFORE ITS DEPENDENCY COUNT IS SET TO 
! ONE  +  MAX.# BATCH STREAMS TO BE SUBMITTED IN THE FOLLOWING SEQUENCE.
!
!FOR EACH JOB CORRESPONDING TO AN UNBUNDLED PRODUCT THE DEPENDENCY
! COUNT IS DECREMENTED BY ONE, EITHER BY THE JOB ITSELF (IF IT GETS
! SUBMITTED) OR IN THIS JOB (IF IT DOESN'T GET SUBMITTED).
!
@SUBMIT VERIF1.BAT/DEPENDENCY:5/OUTPUT:NOLOG
!
!
!IF FORTRA.YES IS PRESENT, DO VERIFICATION OF FORTRAN SYSTEM.
@COPY FORTRA.YES (TO) TTY:
@IF (NOERROR) @GOTO SUBM1::
@QUEUE INP:VERIF1=/MODIFY/DEPENDENCY:-1
@GOTO SUBM2::
!
SUBM1::
!
@SUBMIT VERFOR.BAT/OUTPUT:NOLOG
!
SUBM2::
!
!
!
!IF COBOL.YES IS PRESENT, DO VERIFICATION OF COBOL SYSTEM.
@COPY COBOL.YES (TO) TTY:
@IF (NOERROR) @GOTO SUBM11::
@QUEUE INP:VERIF1=/MODIFY/DEPENDENCY:-1
@GOTO SUBM12::
!
SUBM11::
!
@SUBMIT VERCBL.BAT/OUTPUT:NOLOG
!
SUBM12::
!
!
!
!IF SORT.YES IS PRESENT, DO VERIFICATION OF SORT SYSTEM.
@COPY SORT.YES (TO) TTY:
@IF (NOERROR) @GOTO SUBM2::
@QUEUE INP:VERIF1=/MODIFY/DEPENDENCY:-1
@GOTO SUBM21::
!
SUBM2::
!
@SUBMIT VERSOR.BAT/OUTPUT:NOLOG
!
SUBM21::
!
!
!
!IF BASIC.YES IS PRESENT, DO VERIFICATION OF BASIC SYSTEM.
@COPY BASIC.YES (TO) TTY:
@IF (NOERROR) @GOTO SUBM31::
@QUEUE INP:VERIF1=/MODIFY/DEPENDENCY:-1
@GOTO SUBM32::
!
SUBM31::
!
@SUBMIT VERBAS.BAT/OUTPUT:NOLOG
!
SUBM32::
!
!
!
!***********************************************************
!
%ERR::
@NOERROR
@
@APPEND TTY: (TO) ERRORS.LOG
@
@++++	CONTROL FILE VERIFY.BAT ERROR		++++
@++++	CONTROL HAS REACHED %ERR		++++
@++++	UNEXPECTED ERROR!!!!!			++++
@++++	PLEASE CONSULT FILE VERIFY.LOG		++++
@++++	FOR A MORE DETAILED DIAGNOSIS		++++
@++++	END OF ERROR MESSAGE VERIFY.BAT		++++
@
@
!

!
!************************************************************
%FIN::
!
@NOERROR
@QUEUE INP:VERIF1=/MODIFY/DEPENDENCY:-1
