C	FORTRAN PROGRAM TO CREATE AND PUT A HEADING LINE 
C	IN THE FILE ERRORS.LOG
	DIMENSION X(2),Y(2)
	OPEN (UNIT=20,DEVICE=DSK,ACCESS='SEQOUT',MODE='ASCII',
	1DISPOSE='SAVE',FILE='ERRORS.LOG')
	CALL DATE(X)
	CALL TIME(Y(1),Y(2))
	WRITE (20,100) X(1),X(2),Y(1),Y(2)
100	FORMAT (' ERRORS.LOG ',2A5,' ',2A5,/)
	CLOSE(UNIT=20,DEVICE=DSK,ACCESS='SEQOUT',MODE='ASCII',
	1DISPOSE='SAVE',FILE='ERRORS.LOG')
	END
